kind: ServiceAccount
apiVersion: v1
metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
  annotations:
    {{- if .Values.iam_role }}
    eks.amazonaws.com/role-arn: {{ .Values.iam_role }}
    {{- end }}
